### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by rafaqueque** [busterc/xcv#6]
Hey, is it possible to create a `brew` package for this?

:+1:

**Comment by busterc** [comment]
I just merged a pr that added `bpkg` installation ability. I don't use `brew` but if somebody submits a pr I'll definitely check it out!

**Comment by busterc** [comment]
Oh yeah, this occurred a long time  ago: 88f17c27a314f6e89761c74e90bb9b466a5bc607
